### ISSUE TITLE
kill more redundant functions in epub3

### ISSUE THREAD

**Issue by bdolor** [unit29868/pressbooks#18]
I'd like to see more redundant functions go now that we're extending epub201. One of the things that would facilitate that is to modify the file path to where images/audio/video are stored in the epub. Currently PB stores everything in the directory `'assets'` — proposing to store audio/video in `'assets/video'` and `'assets/audio'`

some example functions on the chopping block would be `createCover()`, `scrapeKneadAndSaveCss()`, etc..

**Comment by dac514** [comment]
I don't understand.

createCover() is important because it affects the order of the manifest, and forcefully ids the cover so that Kindlegen doesn't barf horribly. 

scrapeKnedAndSaveCss() does some pretty non-trivial things as well.

These are not functions that can be thrown away. Edited and refactored, sure no problem. Removed, not so easy.

Please have the foresight to understand that all changes to Epub3 will directly affect Mobi files, which for at PressBooks we care deeply. So, do not gut stuff unless you are sure it works all the way through Kindlegen.

Thanks!

**Comment by bdolor** [comment]
This is only a reference to unnecessarily overriding functions in class epub3 when relying on the parent class will do. Whether or not the specific functions mentioned above will need to remain exact copies of the functions in the parent class has yet to be tested, but stripping out redundancy in class epub3 is the objective in this ticket.

**Comment by dac514** [comment]
Ok, have fun!

**Comment by bdolor** [comment]
class pb-epub3 is now down to 430 lines with zero loss of functionality. All functions that are now there, need to be there, as they must override the parent class.
