### ISSUE TITLE
Check for and eliminate embedded TrueType references

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#7]
When embeding fonts, only WOFF and OpenType are supported. No more TrueType font support.

**Comment by bdolor** [comment]
closing

**Comment by hughmcguire** [comment]
why no ttf?

**Comment by bdolor** [comment]
http://www.idpf.org/epub/30/spec/epub30-changes.html#sec-new-changed-embedded-fonts

I gather EPUB readers aren't required to support ttf.

**Comment by hughmcguire** [comment]
hrm. we are embedding TTF fonts ... with a "fail gracefully" approach (ie, if the embedded font doesn't embed, things should be fine).

I am not sure if "required to support OTF & WOFF" means:
 "...in addition to TTF which you already do" ... 
OR
"...and you can forget about TTF ..."

I'd prefer to leave support for TTF in there since to my knowledge -- and all our testing -- suggests most ereaders that support embedding support TTF.

**Comment by bdolor** [comment]
It's open to both interpretations, I guess. I can't tell you which one is right, but my preference is to read the above guideline explicitly; the absence of TTF means forget about it. Although, epubcheck doesn't complain when I force a .ttf in the epub3. 

Also, the above issue began as an email request from Dac — sent to your gmail account around Oct.11

**Comment by hughmcguire** [comment]
ok... i guess safer to make sure we evolve pressbooks to the newer spec. ... but some thinking to do about all the old reading systems that only support TTF & OTF, not WOFF (I suspect there are many). again, i guess as long as embedded fonts degrade gracefully, it should be OK.

**Comment by hughmcguire** [comment]
FYI, from Bill McCoy, who runs IDPF, which is the standards body in charge of EPUB3. Upshot: PB should migrate to WOFF or OTF, prior to rollout of EPUB3. 

/QUOTE:
This was debated in the EPUB 3 WG but every new format required is a burden to reading system implementors and if not universally supported would not in practice help content authors create interoperable content. TTF fonts can be convered to OpenType (which supports TTF data format) and/or WOFF. Also TrueType is not an official standard and there were (as of 2010) patent considerations but these were as I recall secondary the main issue was just whether to require 1, 2, or 3 formats and we settled on 2 based on recommendations of font vendors and others.

"IMO this was a reasonable decision but while it's arguable (esp. as all major browsers do support TTF) I don't think it's likely to be revisited.

"Note though that use of TTF fonts in EPUB is not illegal it's just not required to be supported and should have an intrinsic fallback (which obviously most CSS font selections do as a matter of course). In practice I think TTF fonts are likely to work on EPUB 3 Reading Systems since 100% of them are buiding on top of browser engines and per above 100% of these still support TTF."
ENDQUOTE/
